### PR TITLE
Create choose-website-or-app.md

### PR DESCRIPTION
**Pull request by IrinaYudovich**
This file provides a high level overview of deciding whether to pursue a site, a mobile site or a native app.

### CODE REVIEW

**Comment by IrinaYudovich** [comment]
@WCCBS2015 Can you please take a look and let me know if you have any edits? 
PS Don't you love this video? [IMAGE ALT TEXT HERE](http://www.youtube.com/watch?v=oPD0L0M7rtA)

**Comment by WCCBS2015** [comment]
Great video and great file! I would add that mobile apps are great for interactivity and gaming. Working on a mobile game now myself [Waynesaw](https://www.kickstarter.com/projects/1228426126/waynesaw)

**Comment by IrinaYudovich** [comment]
@WCCBS2015 I incorporated your suggestions (and added a plug for our friendly little chainsaw), take a look.

**Comment by WCCBS2015** [comment]
:+1: :shipit: high five

**Pull request merged**
