### PR TITLE
Create questions-to-ask-developers-during-hiring.md

### PR DESCRIPTION
**Pull request by WCCBS2015**
List of (primarily non-technical) questions to ask prosepctive developers during hiring process

### CODE REVIEW

**Comment by WCCBS2015** [comment]
@IrinaYudovich Pls review Cat begging

**Comment by IrinaYudovich** [comment]
Looks good. What about adding the 3 q's we discussed in class: 1) What x do you use? 2) What do you compare it to? 3) Why x over why?

**Comment by WCCBS2015** [comment]
Good point. Made the edits. Ready to ship?

**Comment by IrinaYudovich** [comment]
:+1: YAY WE'RE DONE Elaine dancing

**Pull request merged**
